export const datas = [
	{
		status: "invite",
		name: "Boreum Ipsum",
		email: "loreumipsum@techvariable.com",
		phone: "+91 84253 21458",
		designation: "Sr. Programmer Analyst",
		assignTo: "Loreum Ipsum",
	},
	{
		status: "successful",
		name: "Aoreum Ipsum",
		email: "loreumipsum@techvariable.com",
		phone: "+91 84253 21458",
		designation: "Sr. Programmer Analyst",
		assignTo: "Loreum Ipsum",
	},
	{
		status: "pending",
		name: "Freum Ipsum",
		email: "loreumipsum@techvariable.com",
		phone: "+91 84253 21458",
		designation: "Sr. Programmer Analyst",
		assignTo: "Loreum Ipsum",
	},
	{
		status: "invite",
		name: "Doreum Ipsum",
		email: "loreumipsum@techvariable.com",
		phone: "+91 84253 21458",
		designation: "Sr. Programmer Analyst",
		assignTo: "Loreum Ipsum",
	},
	{
		status: "pending",
		name: "Eoreum Ipsum",
		email: "loreumipsum@techvariable.com",
		phone: "+91 84253 21458",
		designation: "Sr. Programmer Analyst",
		assignTo: "Loreum Ipsum",
	},
	{
		status: "successful",
		name: "Loreum Ipsum",
		email: "loreumipsum@techvariable.com",
		phone: "+91 84253 21458",
		designation: "Sr. Programmer Analyst",
		assignTo: "Loreum Ipsum",
	},
	{
		status: "successful",
		name: "Loreum Ipsum",
		email: "loreumipsum@techvariable.com",
		phone: "+91 84253 21458",
		designation: "Sr. Programmer Analyst",
		assignTo: "Loreum Ipsum",
	},
	{
		status: "pending",
		name: "Loreum Ipsum",
		email: "loreumipsum@techvariable.com",
		phone: "+91 84253 21458",
		designation: "Sr. Programmer Analyst",
		assignTo: "Loreum Ipsum",
	},
	{
		status: "pending",
		name: "Loreum Ipsum",
		email: "loreumipsum@techvariable.com",
		phone: "+91 84253 21458",
		designation: "Sr. Programmer Analyst",
		assignTo: "Loreum Ipsum",
	},
	{
		status: "invite",
		name: "Loreum Ipsum",
		email: "loreumipsum@techvariable.com",
		phone: "+91 84253 21458",
		designation: "Sr. Programmer Analyst",
		assignTo: "Loreum Ipsum",
	},
	{
		status: "successful",
		name: "Loreum Ipsum",
		email: "loreumipsum@techvariable.com",
		phone: "+91 84253 21458",
		designation: "Sr. Programmer Analyst",
		assignTo: "Loreum Ipsum",
	},
	{
		status: "successful",
		name: "Loreum Ipsum",
		email: "loreumipsum@techvariable.com",
		phone: "+91 84253 21458",
		designation: "Sr. Programmer Analyst",
		assignTo: "Loreum Ipsum",
	},
	{
		status: "pending",
		name: "Loreum Ipsum",
		email: "loreumipsum@techvariable.com",
		phone: "+91 84253 21458",
		designation: "Sr. Programmer Analyst",
		assignTo: "Loreum Ipsum",
	},
	{
		status: "pending",
		name: "Loreum Ipsum",
		email: "loreumipsum@techvariable.com",
		phone: "+91 84253 21458",
		designation: "Sr. Programmer Analyst",
		assignTo: "Loreum Ipsum",
	},
	{
		status: "invite",
		name: "Loreum Ipsum",
		email: "loreumipsum@techvariable.com",
		phone: "+91 84253 21458",
		designation: "Sr. Programmer Analyst",
		assignTo: "Loreum Ipsum",
	},
];

export default datas;
